/* Generated by xcos2c 0.1 — IR 0.1, diagram "Untitled ". Do not edit. */
#ifndef MIXER_H
#define MIXER_H

#include <stdint.h>
#include "xcos2c_types.h"
#include "xcb_summation.h"

#define MIXER_DT 0.00050000000000000001

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    real_t thro_des;
    real_t roll_pid;
    real_t pitch_pid;
    real_t yaw_pid;
} mixer_in_t;

typedef struct {
    real_t m1;
    real_t m2;
    real_t m3;
    real_t m4;
} mixer_out_t;

typedef struct {
    real_t s17_1[1];
    real_t s18_1[1];
    real_t s19_1[1];
    real_t s20_1[1];
} mixer_ctx_t;

void mixer_init(mixer_ctx_t *ctx);
void mixer_step(mixer_ctx_t *ctx, const mixer_in_t *in, mixer_out_t *out);

#ifdef __cplusplus
}
#endif

#endif /* MIXER_H */
