/* Generated by xcos2c 0.1 — IR 0.1, diagram "Untitled ". Do not edit. */
#include "mixer.h"

static const int b17_signs[4] = {1, -1, 1, 1};
static const int b18_signs[4] = {1, -1, -1, -1};
static const int b19_signs[4] = {1, 1, -1, 1};
static const int b20_signs[4] = {1, 1, 1, -1};
static const xcb_summation_params_t b17_p = {4, 1, b17_signs};
static const xcb_summation_params_t b18_p = {4, 1, b18_signs};
static const xcb_summation_params_t b19_p = {4, 1, b19_signs};
static const xcb_summation_params_t b20_p = {4, 1, b20_signs};

void mixer_init(mixer_ctx_t *ctx)
{
    (void)ctx;
}

void mixer_step(mixer_ctx_t *ctx, const mixer_in_t *in, mixer_out_t *out)
{
    xcb_summation_step(&b17_p, (const real_t *const[]){&in->thro_des, &in->pitch_pid, &in->roll_pid, &in->yaw_pid}, (real_t *const[]){ctx->s17_1});
    xcb_summation_step(&b18_p, (const real_t *const[]){&in->thro_des, &in->pitch_pid, &in->roll_pid, &in->yaw_pid}, (real_t *const[]){ctx->s18_1});
    xcb_summation_step(&b19_p, (const real_t *const[]){&in->thro_des, &in->pitch_pid, &in->roll_pid, &in->yaw_pid}, (real_t *const[]){ctx->s19_1});
    xcb_summation_step(&b20_p, (const real_t *const[]){&in->thro_des, &in->pitch_pid, &in->roll_pid, &in->yaw_pid}, (real_t *const[]){ctx->s20_1});
    out->m1 = ctx->s17_1[0];
    out->m2 = ctx->s18_1[0];
    out->m3 = ctx->s19_1[0];
    out->m4 = ctx->s20_1[0];
}
